apiVersion: apps/v1
kind: Deployment
metadata:
  name: tick-fetcher-decoupler
  namespace: grift-dev
  labels:
    app: tick-fetcher-decoupler
    environment: development
spec:
  replicas: 1  # Singleton deployment
  selector:
    matchLabels:
      app: tick-fetcher-decoupler
  template:
    metadata:
      labels:
        app: tick-fetcher-decoupler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: tick-fetcher-sa
      containers:
      - name: tick-fetcher-decoupler
        image: gcr.io/grift-forex/tick-fetcher-decoupler:latest
        imagePullPolicy: Always
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "grift-forex"
        - name: ENVIRONMENT
          value: "development"
        - name: OANDA_ENVIRONMENT
          value: "practice"  # Use practice environment in dev
        - name: DEBUG
          value: "true"
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: tick-fetcher-decoupler
  namespace: grift-dev
  labels:
    app: tick-fetcher-decoupler
spec:
  ports:
  - port: 8080
    targetPort: http
    name: http
  selector:
    app: tick-fetcher-decoupler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tick-fetcher-sa
  namespace: grift-dev
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tick-fetcher-decoupler
  namespace: grift-dev
  labels:
    app: tick-fetcher-decoupler
spec:
  selector:
    matchLabels:
      app: tick-fetcher-decoupler
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
